version: '3'

services:
    nginx:
        image: nginx:latest
        restart: on-failure
        volumes:
            - './public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - "8000:80"
            - "443:443"
        depends_on:
            - php
    php:
        build:
          context: .
          dockerfile: docker/php/Dockerfile
        volumes:
            - './:/usr/src/app'
        restart: on-failure
        user: 1000:1000
    db:
        image: mysql:latest
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "4v732ZJP6YcV2UcI"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "test1"
            MYSQL_ROOT_HOST: "%"
