#index:
#    path: /
#    controller: App\Controller\DefaultController::index
user_register:
  path: /api/register
  controller: App\Controller\AuthController::register
  methods: [ 'POST' ]
authentication_token:
  path: /api/login_check
  methods: ['POST']
api_graphql_entrypoint:
  path: /api/graphql
  controller: api_platform.graphql.action.entrypoint
graphiql:
  path: /api/docs/graphiql
  controller: api_platform.graphql.action.graphiql
graphql_playground:
  path: /api/docs/graphql_playground
  controller: api_platform.graphql.action.graphql_playground